name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Build JAR
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Upload JAR to Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/libs/ssl-diagnostic-tool.jar
